---
categorical_dropdown_byob:
  label: Categorical Variable  
  dropdown_list:
    - 
      label: Region
      value: site_region
    - 
      label: State or Province
      value: site_state_province
    - 
      label: IBC Construction Type
      value: bldg_ibc_type
    - 
      label: Attached Parking Type
      value: bldg_park_type
    - 
      label: Primary Building Use Type
      value: bldg_prim_use
    - 
      label: Stories Above Grade
      value: bldg_stories_above
    - 
      label: Stories Below Grade
      value: bldg_stories_below
    - 
      label: Building Height
      value: bldg_height
    - 
      label: Seismic Design Category
      value: str_sdc
    - 
      label: Primary Horizontal Gravity System
      value: str_prim_horiz_sys
    - 
      label: Primary Vertical Gravity System
      value: str_prim_vert_sys
    - 
      label: Primary Lateral Force Resisting System
      value: str_lat_sys
    - 
      label: Foundation Type
      value: str_fdn_type
    - 
      label: Structural System Summary
      value: str_sys_summary
    - 
      label: Design Phase
      value: lca_design_phase
    - 
      label: Software
      value: lca_software
    - 
      label: Physical Scope Summary
      value: lca_phys_scope
  first_item: bldg_prim_use
  dropdown_id: categorical_dropdown_byob
  tooltip: Categorical values are those that can take on 
    one of a limited number of possible values. These values will 
    become the categories plotted on the y-axis of the box plot.
  tooltip_id: categorical_dropdown_byob_tooltip

total_impact_dropdown_byob: 
  label: Impacts  
  dropdown_list: 
    - 
      label: Embodied Carbon Intensity
      value: Embodied Carbon Intensity
    -  
      label: Eutrophication Potential Intensity
      value: Eutrophication Potential Intensity
    -  
      label: Acidification Potential Intensity
      value: Acidification Potential Intensity
    -  
      label: Smog Formation Potential Intensity
      value: Smog Formation Potential Intensity
    -  
      label: Ozone Depletion Potential Intensity
      value: Ozone Depletion Potential Intensity
    -  
      label: Natural Resource Depletion Intensity
      value: Natural Resource Depletion Intensity
  first_item: Embodied Carbon Intensity
  dropdown_id: total_impact_dropdown_byob
  tooltip: Each environmental metric contained in the dataset
    is represented in this dropdown. They are either divided by
    floor area to create "intensity" metrics, or are divided by
    other numeric values such as occupants or residential units. 
    These values will be plotted on the y-axis of the graph.
  tooltip_id: total_impact_dropdown_tooltip_byob

enable_filters_toggle:
  label: ""
  toggle_list:
    - label: Enable categorical filtering
      value: 1
  first_item: []
  toggle_id: enable_filters_toggle
  tooltip: This toggle enable you to filter projects based on the 
    categorical filters chosed in the dropdown below.
  tooltip_id: enable_filters_toggle_tooltip

new_constr_toggle_byob:
  label: ""
  toggle_list:
    - label: New construction only 
      value: 1
  first_item: []
  toggle_id: new_constr_toggle_byob
  tooltip: This toggle will remove projects with
    a project type of "Minor Renovation", "Major Renovation",
    or "Tenant Improvement".
  tooltip_id: new_constr_toggle_tooltip_byob

outlier_toggle_byob:
  label: ""
  toggle_list:
    - label: Crop outliers 
      value: 1
  first_item: []
  toggle_id: outlier_toggle_byob
  tooltip: This toggle will Crop outliers from the box plot.
    A project is considered an outlier if the selected impact or continuous variable
    of the project is 3 times the interquartile range of 
    all project impacts in the dataset.
  tooltip_id: outlier_toggle_tooltip_byob

floor_area_normalization_byob:
  label: "Normalize intensity by:  "
  radio_list:
    - label: Constructed Floor Area
      value: bldg_cfa
    - label: Gross Internal Floor Area
      value: bldg_gfa
  first_item: bldg_gfa
  radio_id: floor_area_normal_byob
  tooltip: "Total constructed floor area (CFA) 
    includes the gross internal floor area (GFA) of the 
    building and the gross floor area of any 
    attached/integrated parking components."
  tooltip_id: floor_area_normalization_tooltip_byob

sort_box_plot_byob:
  label: "Sort box plots by:  "
  radio_list:
    - label: Median
      value: median
    - label: Categorical value
      value: cat_value
    - label: Sample Size
      value: sample_size
  first_item: median
  radio_id: sort_box_plot_byob
  tooltip: Selecting "Median" sorts box plots from 
    highest to lowest median values. Selecting "Categorical 
    value" will sort the box plots in a rational
     way based on the category (e.g. Seismic Design Category 
     will be sorted alphabetically)
  tooltip_id: sort_box_plot_tooltip_cat


field_name_map:
  site_country: Country
  site_region: Region
  site_state_province: State or Province
  site_clim_zone: Climate Zone
  bldg_proj_type: Project Type
  bldg_ibc_type: IBC Construction Type
  bldg_park_type: Attached Parking Type
  bldg_prim_use: Primary Building Use Type
  bldg_sec_use: Secondary Building Use Type
  bldg_stories_above: Stories Above Grade
  bldg_stories_below: Stories Below Grade
  bldg_height: Building Height
  str_seis_site_cls: Seismic Site Class
  str_sdc: Seismic Design Category
  str_prim_horiz_sys: Primary Horizontal Gravity System
  str_prim_vert_sys: Primary Vertical Gravity System
  str_lat_sys: Primary Lateral Force Resisting System
  str_podium: Podium
  str_fdn_type: Foundation Type
  str_sys_summary: Structural System Summary
  lca_design_phase: Design Phase
  lca_software: Software
  lca_purp_of_assessment: Purpose of Assessment
  lca_phys_scope: Physical Scope Summary
  lca_ec_reductions: Embodied Carbon Reductions
  eci_a_to_c_gfa: Embodied Carbon Intensity
  epi_a_to_c_gfa: Eutrophication Potential Intensity
  api_a_to_c_gfa: Acidification Potential Intensity
  sfpi_a_to_c_gfa: Smog Formation Potential Intensity
  odpi_a_to_c_gfa: Ozone Depletion Potential Intensity
  nredi_a_to_c_gfa: Natural Resource Depletion Intensity
  eci_a_to_c_cfa: Embodied Carbon Intensity
  epi_a_to_c_cfa: Eutrophication Potential Intensity
  api_a_to_c_cfa: Acidification Potential Intensity
  sfpi_a_to_c_cfa: Smog Formation Potential Intensity
  odpi_a_to_c_cfa: Ozone Depletion Potential Intensity
  nredi_a_to_c_cfa: Natural Resource Depletion Intensity
  ec_per_occupant_a_to_c: Embodied Carbon per Occupant
  ec_per_res_unit_a_to_c: Embodied Carbon per Residential Unit
  bldg_cfa: Constructed Floor Area
  bldg_gfa: Gross Floor Area
  bldg_park_gfa: Parking Floor Area
  bldg_added_gfa: Added Floor Area
  bldg_renovated_gfa: Renovated Floor Area
  bldg_occupants: Occupants
  bldg_res_units: Residential Units
  bldg_therm_env_area: Thermal Envelope Area
  bldg_wwr: Window-to-Wall Ratio
  bldg_rval_walls: Average R-Value of Walls
  bldg_rval_roofs: Average R-Value of Roofs
  str_wind_speed: Ultimate Wind Speed
  str_grid_long: Typical Column Grid, Long Direction
  str_grid_short: Typical Column Grid, Short Direction
  lca_ec_reduction_percent: Embodied Carbon Reduction Percentage
  median: median
  sample_size: sample size 
  cat_value: predetermined categorical values
  All: Selected Project Types

category_order_map:
  site_country:
    - United States
    - Canada
  site_region:
    - Eastern
    - South Eastern
    - Great Lakes Midwest
    - North Central
    - South Central
    - Rocky Mountains
    - Pacific Northwest
    - Pacific Southwest
    - Canada
  site_state_province:
    - Massachusetts
    - New York
    - Pennsylvania
    - Texas
    - Colorado
    - British Columbia
    - Washington
    - Oregon
    - California
  site_clim_zone:
    - Zone 1A (Very Hot Humid)
    - Zone 2A (Hot Humid)
    - Zone 2B (Hot Dry)
    - Zone 3A (Warm Humid)
    - Zone 3B (Warm Dry)
    - Zone 3C (Warm Marine)
    - Zone 4A (Mixed Humid)
    - Zone 4C (Mixed Marine)
    - Zone 5A (Cool Humid)
    - Zone 5B (Cool Dry)
    - Zone 6A (Cold Humid)
    - Zone 6B (Cold Dry)
    - Zone 7 (Very Cold)
    - Zone 8 (Subarcitc/Arctic)
    - Can. 4 (<3000 HDD)
    - Can. 7B (6000-6999 HDD)
  bldg_proj_type:
    - New Construction
    - Major Renovation
    - Minor Renovation
    - Tenant Improvement
  bldg_ibc_type:
    - Type I-A
    - Type I-B
    - Type II-A
    - Type II-B
    - Type III-A
    - Type III-B
    - Type IV-B
    - Type IV-C
    - Type IV-HT
    - Type V-A
    - Type V-B
  bldg_park_type: 
    - No Parking
    - Above grade, within footprint of main structure
    - Above grade, attached to main structure
    - Below Grade
  bldg_prim_use: 
    - Office
    - Education
    - "Residential: Multifamily (5 or more units)"
    - Public Assembly
    - Laboratory
    - Warehouse and Storage
    - Healthcare
    - Public Order and Safety
    - Transportation Hub
    - Lodging
    - Mercantile
    - Parking
    - Industrial
    - Food Service
    - Religious Worship
    - Other
  bldg_sec_use:
    - Mercantile
    - Office
    - Other
    - Public Assembly
    - Education
    - Food Service
    - Education
    - Warehouse and Storage
    - Laboratory
    - Healthcare
    - Public Order and Safety
    - Religious Worship
    - "Residential: Multifamily (2-4 units)"
  bldg_stories_above:
    - 1 story
    - 2 to 5 stories
    - 6 to 10 stories
    - 11 to 15 stories
    - 16 to 20 stories
    - 21 or more stories
  bldg_stories_below:
    - 0 stories
    - 1 story
    - 2 stories
    - 3 stories
    - 4 or more stories
  bldg_height:
    - 0-7.5 m
    - 7.6-15 m
    - 15.1-22.5 m
    - 22.6-30 m
    - 31-45 m
    - 46-60 m
    - 61-90 m
    - Over 90 m
  str_seis_site_cls:
    - A
    - B
    - C
    - D
    - E
    - F
  str_sdc:
    - A
    - B
    - C
    - D
    - E
    - F
  str_prim_horiz_sys:
    - "Concrete: PT framing"
    - "Concrete: Non-PT framing"
    - "Concrete: Precast"
    - "Concrete: Other"
    - "Steel: Frame + concrete on metal deck"
    - "Steel: Frame + bare metal deck"
    - "Steel: Other"
    - "Wood: Joists and sheathing"
    - "Wood: Engineered panels"
    - "Wood: Other"
  str_prim_vert_sys:
    - "Concrete: CIP"
    - "Concrete: Precast"
    - "Concrete: Other"
    - "Steel: Columns"
    - "Steel: Cold-formed"
    - "Wood: Mass timber"
    - "Wood: Light-frame"
    - "Wood: Other"
    - Masonry
  str_lat_sys:
    - "Concrete: Shear walls"
    - "Concrete: Moment frames"
    - "Concrete: Other"
    - "Steel: Braced frames"
    - "Steel: Moment frames"
    - "Steel: Other"
    - Light Frame shear panels
    - "Masonry: Shear walls"
    - "Wood: Shear panels"
    - "Wood: Other"
  str_podium:
    - Not a podium building
    - Primary system defined above is on a podium
    - Primary system defined above is a podium
  str_fdn_type:
    - Shallow foundation
    - Deep foundation < 50' (15m)
    - Deep foundation > 50' (15m)
    - Other Foundation System
  str_sys_summary:
    - Concrete
    - Steel
    - Steel/Concrete
    - Steel/Masonry
    - "Wood: Mass Timber"
    - "Wood: Light-frame"
    - Other
  lca_design_phase:
    - Design Development
    - Construction Documents
    - Construction
    - Completed
  lca_software:
    - Tally LCA
    - One Click LCA
  lca_purp_of_assessment:
    - "Required: Client Directive"
    - "Required: Governing Policy"
    - "Required: LEED Proposed"
    - "Required: ILFI Proposed"
    - "Required: Other"
    - "Voluntary: Design Milestone Tracking"
    - "Voluntary: Hot Spot Analysis"
    - "Voluntary: Performance Declaration"
    - "Voluntary: Design Iteration Analysis"
    - "Voluntary: Internal Benchmarking"
    - "Voluntary: Other"
  lca_phys_scope:
    - BSE
    - BSEC
    - BSEF
    - BSECF
    - SCF
    - ECF
    - SEC
    - SECF
    - CF
  lca_ec_reductions:
    - Yes
    - No
  
lcs_checklist: 
  label: Life Cycle Stage 
  checklist: 
    - 
      label: A1-A3
      value: A1-A3
    -  
      label: A4
      value: A4
    -  
      label: B4-B5
      value: B4-B5
    -  
      label: C2-C4
      value: C2-C4
    -  
      label: D
      value: D
  first_item: [A1-A3, A4, B4-B5, C2-C4]
  checklist_id: lcs_checklist
  tooltip: TBD
  tooltip_id: TBD

scope_checklist: 
  label: Scope  
  checklist: 
    - 
      label: Substructure
      value: Substructure
    -  
      label: "Shell - Superstructure"
      value: "Shell - Superstructure"
    -  
      label: "Shell - Enclosure"
      value: "Shell - Enclosure"
    -  
      label: "Interiors - Finishes"
      value: "Interiors - Finishes"
    -  
      label: "Interiors - Construction"
      value: "Interiors - Construction"
    -  
      label: "Unknown"
      value: "Unknown"
  first_item: ["Substructure", "Shell - Superstructure", "Shell - Enclosure"]
  checklist_id: scope_checklist
  tooltip: TBD
  tooltip_id: TBD

proj_type_checklist: 
  label: Project Type  
  checklist: 
    - 
      label: New Construction
      value: New Construction
    -  
      label: Major Renovation
      value: Major Renovation
    -  
      label: Minor Renovation
      value: Minor Renovation
    -  
      label: Tenant Improvement
      value: Tenant Improvement
  first_item: [New Construction]
  checklist_id: proj_type_checklist
  tooltip: TBD
  tooltip_id: TBD

line_toggle_byob:
  label: ""
  toggle_list:
    - label: Enable reference line
      value: 1
  first_item: []
  toggle_id: ref_line_toggle
  tooltip: TBD
  tooltip_id: TBD

line_number_input:
  label: Value of vertical line
  placeholder: Integer 
  input_id: line_number_input
  tooltip: TBD
  tooltip_id: TBD

line_name_input:
  label: Name of reference value
  placeholder: Text 
  input_id: line_name_input
  tooltip: TBD
  tooltip_id: TBD

caption_orders:
  scope_order:
    - Substructure
    - "Shell - Superstructure"
    - "Shell - Enclosure"
    - "Interiors - Construction"
    - "Interiors - Finishes"
    - Unknown
  proj_type_order:
    - New Construction
    - Major Renovation
    - Minor Renovation
    - Tenant Improvement
  
cat_selection_toggle_byob:
  label: ""
  toggle_list:
    - label: Enable categorical selection
      value: 1
  first_item: [1]
  toggle_id: cat_selection_toggle_byob
  tooltip: TBD
  tooltip_id: TBD

cat_filter:
  label: Categorical values to filter
  dropdown_list:
  first_item:
  dropdown_id: cat_filter
  placeholder: If enabled, please select a filter
  tooltip: TBD
  tooltip_id: TBD

second_cat_selection_toggle:
  label: ""
  toggle_list:
    - label: Enable second categorical selection
      value: 1
  first_item: []
  toggle_id: second_cat_selection_toggle
  tooltip: TBD
  tooltip_id: TBD

second_cat_dropdown:
  label: Second categorical variable
  dropdown_list:
  first_item:
  dropdown_id: second_cat_dropdown
  tooltip: TBD
  tooltip_id: TBD

second_cat_filter_toggle:
  label: ""
  toggle_list:
    - label: Enable second categorical filter
      value: 1
  first_item: []
  toggle_id: second_cat_filter_toggle
  tooltip: TBD
  tooltip_id: TBD

second_cat_filter:
  label: Second categorical values to filter
  dropdown_list:
  first_item:
  dropdown_id: second_cat_filter
  placeholder: If enabled, please select a filter
  tooltip: TBD
  tooltip_id: TBD

mat_filter_toggle_byob:
  label: ""
  toggle_list:
    - label: Enable material selection
      value: 1
  first_item: []
  toggle_id: mat_filter_toggle_byob
  tooltip: TBD
  tooltip_id: TBD

mat_filter:
  label: Materials to filter
  dropdown_list:
  first_item:
  dropdown_id: mat_filter
  placeholder: If enabled, please select a filter
  tooltip: TBD
  tooltip_id: TBD

material_list: 
  - Acoustic ceilings
  - Adhesives and sealants
  - Air and vapor barriers
  - Aluminum
  - Applied fireproofing
  - Cladding
  - Coatings
  - Concrete
  - Doors and frames
  - Flooring and tile
  - Glazing
  - Gypsum
  - Insulation  
  - Masonry
  - Other
  - Other metals
  - Roofing and waterproofing
  - Steel
  - Synthetic composites
  - Wall coverings
  - Windows and frames
  - Wood and composites
