---
i_d: 
  label: Impacts  
  dropdown_list: 
    - 
      label: Global Warming Potential
      value: 1
    -
      label: Material Use
      value: 2
    -  
      label: Eutrophication Potential
      value: 3
    -  
      label: Acidification Potential
      value: 4
    -  
      label: Smog Formation Potential
      value: 5
    -  
      label: Ozone Depletion Potential
      value: 6
    -  
      label: Non Renewable Energy Demand
      value: 7
  first_item: 1
  dropdown_id: i_d
  tooltip: Select an environmental impact category to assess.
    Each metric is calculated as an “intensity” where each 
    project’s total impact has been divided by its floor area. 
    These values will be plotted on the y-axis of the graph.
  tooltip_id: i_d_tooltip
  value_map:
    1: Global Warming Potential
    2: Material Use
    3: Eutrophication Potential
    4: Acidification Potential
    5: Smog Formation Potential
    6: Ozone Depletion Potential
    7: Non Renewable Energy Demand

i_typ:
  label: "Impact type"
  radio_list:
    - label: Impact Intensity
      value: 1
    - label: Total Impact
      value: 2
  first_item: 1
  radio_id: i_typ
  tooltip: Use this selection to select the type of environmental impact
    to be shown in the box plots. Selecting "Impact Intensity" will display
    the total environmental impact divided by the area metric selected below in 
    "Additional Filters". Selecting "Total Impact" will display the total 
    environmental impact of each project.
  tooltip_id: i_typ_tooltip

lcs_c: 
  label: Life Cycle Stage 
  checklist: 
    - 
      label: A1-A3
      value: 1
    -  
      label: A4
      value: 2
    -  
      label: B4-B5
      value: 3
    -  
      label: C2-C4
      value: 4
    -  
      label: D
      value: 5
  first_item: [1, 2, 3, 4]
  checklist_id: lcs_c
  tooltip: Filter which life cycle stages to display by
    checking each box. Note that not all projects contain 
    life cycle stage D results. 
  tooltip_id: lcs_c_tooltip
  value_map:
    1: A1-A3
    2: A4
    3: B4-B5
    4: C2-C4
    5: D

sc_c: 
  label: Element scope  
  checklist: 
    - 
      label: Substructure
      value: 1
    -  
      label: "Shell - Superstructure"
      value: 2
    -  
      label: "Shell - Enclosure"
      value: 3
    -  
      label: "Interiors - Construction"
      value: 4
    -  
      label: "Interiors - Finishes"
      value: 5
    -  
      label: "Unknown"
      value: 6
  first_item: [1, 2, 3]
  checklist_id: sc_c
  tooltip: Filter which building elements to display. These 
    element scopes are derived from Omniclass Table 21. 
    All new construction projects contain Substructure, 
    Superstructure, and Enclosure at a minimum.
  tooltip_id: sc_c_tooltip
  value_map:
    1: Substructure
    2: "Shell - Superstructure"
    3: "Shell - Enclosure"
    4: "Interiors - Construction"
    5: "Interiors - Finishes"
    6: "Unknown"

p_typ_c: 
  label: Project Type  
  checklist: 
    - 
      label: New Construction
      value: 1
    -  
      label: Major Renovation
      value: 2
    -  
      label: Minor Renovation
      value: 3
    -  
      label: Tenant Improvement
      value: 4
  first_item: [1]
  checklist_id: p_typ_c
  tooltip: Filter which project types to display. 
    New construction is the default for this option, 
    but any combination of renovations can be selected 
    as well. Note that different project types may 
    include significant differences in their scope 
    of work that limit comparability.
  tooltip_id: p_typ_c_tooltip
  value_map:
    1: New Construction
    2: Major Renovation
    3: Minor Renovation
    4: Tenant Improvement

c_t_1:
  label: ""
  toggle_list:
    - label: Enable 1st categorical selection
      value: 1
  first_item: [1]
  toggle_id: c_t_1
  tooltip: Use this toggle to display 
    results of a categorical variable. When enabled, 
    users should select the variable they 
    wish to display below. 
  tooltip_id: c_t_1_tooltip

c_d_1:
  label: 1st categorical variable  
  dropdown_list:
    - 
      label: Region
      value: site_region
    - 
      label: State or Province
      value: site_state_province
    - 
      label: IBC Construction Type
      value: bldg_ibc_type
    - 
      label: Attached Parking Type
      value: bldg_park_type
    - 
      label: Primary Building Use Type
      value: bldg_prim_use
    - 
      label: Stories Above Grade
      value: bldg_stories_above
    - 
      label: Stories Below Grade
      value: bldg_stories_below
    - 
      label: Building Height
      value: bldg_height
    - 
      label: Seismic Design Category
      value: str_sdc
    - 
      label: Primary Horizontal Gravity System
      value: str_prim_horiz_sys
    - 
      label: Primary Vertical Gravity System
      value: str_prim_vert_sys
    - 
      label: Primary Lateral Force Resisting System
      value: str_lat_sys
    - 
      label: Foundation Type
      value: str_fdn_type
    - 
      label: Structural System Summary
      value: str_sys_summary
    - 
      label: Design Phase
      value: lca_design_phase
    - 
      label: Software
      value: lca_software
    - 
      label: Physical Scope Summary
      value: lca_phys_scope
  first_item: bldg_prim_use
  dropdown_id: c_d_1
  tooltip: Use this dropdown to select a categorical 
    variable to display. These values will become the 
    categories plotted on the y-axis of the box plot.
  tooltip_id: c_d_1_tooltip

c_f_t_1:
  label: ""
  toggle_list:
    - label: Enable 1st categorical filtering
      value: 1
  first_item: []
  toggle_id: c_f_t_1
  tooltip: Use this toggle to filter the selected
    categorical variable by the specific groups it contains. 
  tooltip_id: c_f_t_1_tooltip

c_f_1:
  label: 1st categorical filter(s)
  dropdown_list:
  first_item: []
  dropdown_id: c_f_1
  placeholder: If enabled, please select a filter
  tooltip: Use this dropdown to filter the values
    of the first categorical variable to specific 
    groups it contains. If no values are selected, 
    all box plots of the first categorical variable 
    will be plotted.
  tooltip_id: c_f_1_tooltip

c_t_2:
  label: ""
  toggle_list:
    - label: Enable 2nd categorical selection
      value: 1
  first_item: []
  toggle_id: c_t_2
  tooltip: Use this toggle to display
    results grouped by color by a second categorical 
    variable. When enabled, users should select the 
    variable they wish to display below.
  tooltip_id: c_t_2_tooltip

c_d_2:
  label: 2nd categorical variable
  dropdown_list: []
  first_item: []
  dropdown_id: c_d_2
  tooltip: Use this dropdown to select a second categorical
    variable. These values will become the 
    colors of the boxes plotted per first categorical 
    variable.
  tooltip_id: c_d_2_tooltip

c_f_t_2:
  label: ""
  toggle_list:
    - label: Enable 2nd categorical filtering
      value: 1
  first_item: []
  toggle_id: c_f_t_2
  tooltip: Use this toggle to filter the second categorical
    variable by the specific groups it contains.
  tooltip_id: c_f_t_2_tooltip

c_f_2:
  label: 2nd categorical filter(s)
  dropdown_list:
  first_item: []
  dropdown_id: c_f_2
  placeholder: If enabled, please select a filter
  tooltip: Use this dropdown to filter the values of
    the second categorical variable to specific groups
    it contains. If no values are selected, all colored 
    boxes of the second categorical variable 
    will be plotted.
  tooltip_id: c_f_2_tooltip

m_t:
  label: ""
  toggle_list:
    - label: Enable material selection
      value: 1
  first_item: []
  toggle_id: m_t
  tooltip: Use this toggle to display a
    subset of impacts based on a specific material or 
    materials. When enabled, users should select the 
    materials they wish to display below.
  tooltip_id: m_t_tooltip

m_f:
  label: Material filter(s)
  dropdown_list:
  first_item: []
  dropdown_id: m_f
  placeholder: If enabled, please select a filter
  tooltip: Use this dropdown to filter the impacts of 
    projects by material. If no values are selected, the impacts of all materials will be plotted. 
  tooltip_id: m_f_tooltip

fl_no:
  label: "Normalize intensity by: "
  radio_list:
    - label: Built Floor Area
      value: bldg_cfa
    - label: Gross Internal Floor Area
      value: bldg_gfa
  first_item: bldg_gfa
  radio_id: fl_no
  tooltip: Total built floor area includes the 
    gross internal floor area (GFA) of the building and the 
    gross floor area of any attached/integrated parking components. 
    GFA excludes the area of the attached/integrated parking 
    components.
  tooltip_id: fl_no_tooltip

sort_v:
  label: "Sort box plots by:  "
  radio_list:
    - label: Median
      value: median
    - label: Categorical value
      value: cat_value
    - label: Sample Size
      value: sample_size
  first_item: median
  radio_id: sort_v
  tooltip: Use this selection to control how the order of 
    the categories in the y-axis is displayed. Selecting 
    "Median" sorts box plots from highest to lowest median 
    values. Selecting "Categorical value" sorts the box 
    plots in a rational way based on the category (e.g. 
    Seismic Design Category will be sorted alphabetically). 
    Selecting “Sample size” sorts the box plots by the 
    number of projects in a given category.
  tooltip_id: sort_v_tooltip

out_t:
  label: ""
  toggle_list:
    - label: Crop outliers 
      value: 1
  first_item: []
  toggle_id: out_t
  tooltip: Use this toggle to visually crop outliers from 
    the box plot. This will not change the calculated values, 
    as outliers are always included in the calculation of 
    statistics presented in the plots. A project is considered 
    an outlier if the selected impact or continuous variable
    of the project is 3 times the interquartile range of all 
    project impacts in the dataset.
  tooltip_id: out_t_tooltip

ln_t:
  label: ""
  toggle_list:
    - label: Enable reference line
      value: 1
  first_item: []
  toggle_id: ln_t
  tooltip: Use this toggle to add a 
    user-defined reference line to the box plots. This will 
    allow for a visual comparison of a target value across 
    the box plot figures.
  tooltip_id: ln_t_tooltip

ln_v:
  label: Value of reference line
  placeholder: Integer 
  input_id: ln_v
  tooltip: This value corresponds with the x-axis placement 
    of the user-defined vertical line.
  tooltip_id: ln_v_tooltip


ln_nm:
  label: Name of reference value
  placeholder: Text 
  input_id: ln_nm
  tooltip: This value allows for naming and 
    labelling of the user-defined vertical line. 
  tooltip_id: ln_nm_tooltip

# dictionaries for renaming
field_name_map:
  site_country: Country
  site_region: Region
  site_state_province: State or Province
  site_clim_zone: Climate Zone
  bldg_proj_type: Project Type
  bldg_ibc_type: IBC Construction Type
  bldg_park_type: Attached Parking Type
  bldg_prim_use: Primary Building Use Type
  bldg_sec_use: Secondary Building Use Type
  bldg_stories_above: Stories Above Grade
  bldg_stories_below: Stories Below Grade
  bldg_height: Building Height
  str_seis_site_cls: Seismic Site Class
  str_sdc: Seismic Design Category
  str_prim_horiz_sys: Primary Horizontal Gravity System
  str_prim_vert_sys: Primary Vertical Gravity System
  str_lat_sys: Primary Lateral Force Resisting System
  str_podium: Podium
  str_fdn_type: Foundation Type
  str_sys_summary: Structural System Summary
  lca_design_phase: Design Phase
  lca_software: Software
  lca_purp_of_assessment: Purpose of Assessment
  lca_phys_scope: Physical Scope Summary
  lca_ec_reductions: Embodied Carbon Reductions
  eci_a_to_c_gfa: Embodied Carbon Intensity
  epi_a_to_c_gfa: Eutrophication Potential Intensity
  api_a_to_c_gfa: Acidification Potential Intensity
  sfpi_a_to_c_gfa: Smog Formation Potential Intensity
  odpi_a_to_c_gfa: Ozone Depletion Potential Intensity
  nredi_a_to_c_gfa: Natural Resource Depletion Intensity
  eci_a_to_c_cfa: Embodied Carbon Intensity
  epi_a_to_c_cfa: Eutrophication Potential Intensity
  api_a_to_c_cfa: Acidification Potential Intensity
  sfpi_a_to_c_cfa: Smog Formation Potential Intensity
  odpi_a_to_c_cfa: Ozone Depletion Potential Intensity
  nredi_a_to_c_cfa: Natural Resource Depletion Intensity
  ec_per_occupant_a_to_c: Embodied Carbon per Occupant
  ec_per_res_unit_a_to_c: Embodied Carbon per Residential Unit
  bldg_cfa: Built Floor Area
  bldg_gfa: Gross Floor Area
  bldg_park_gfa: Parking Floor Area
  bldg_added_gfa: Added Floor Area
  bldg_renovated_gfa: Renovated Floor Area
  bldg_occupants: Occupants
  bldg_res_units: Residential Units
  bldg_therm_env_area: Thermal Envelope Area
  bldg_wwr: Window-to-Wall Ratio
  bldg_rval_walls: Average R-Value of Walls
  bldg_rval_roofs: Average R-Value of Roofs
  str_wind_speed: Ultimate Wind Speed
  str_grid_long: Typical Column Grid, Long Direction
  str_grid_short: Typical Column Grid, Short Direction
  lca_ec_reduction_percent: Embodied Carbon Reduction Percentage
  median: median
  sample_size: sample size 
  cat_value: predetermined categorical values
  All: Selected Project Types

category_order_map:
  site_country:
    - United States
    - Canada
  site_region:
    - Eastern
    - South Eastern
    - Great Lakes Midwest
    - North Central
    - South Central
    - Rocky Mountains
    - Pacific Northwest
    - Pacific Southwest
    - Canada
  site_state_province:
    - Massachusetts
    - New York
    - Pennsylvania
    - Texas
    - Colorado
    - British Columbia
    - Washington
    - Oregon
    - California
  site_clim_zone:
    - Zone 1A (Very Hot Humid)
    - Zone 2A (Hot Humid)
    - Zone 2B (Hot Dry)
    - Zone 3A (Warm Humid)
    - Zone 3B (Warm Dry)
    - Zone 3C (Warm Marine)
    - Zone 4A (Mixed Humid)
    - Zone 4C (Mixed Marine)
    - Zone 5A (Cool Humid)
    - Zone 5B (Cool Dry)
    - Zone 6A (Cold Humid)
    - Zone 6B (Cold Dry)
    - Zone 7 (Very Cold)
    - Zone 8 (Subarcitc/Arctic)
    - Can. 4 (<3000 HDD)
    - Can. 7B (6000-6999 HDD)
  bldg_proj_type:
    - New Construction
    - Major Renovation
    - Minor Renovation
    - Tenant Improvement
  bldg_ibc_type:
    - Type I-A
    - Type I-B
    - Type II-A
    - Type II-B
    - Type III-A
    - Type III-B
    - Type IV-B
    - Type IV-C
    - Type IV-HT
    - Type V-A
    - Type V-B
  bldg_park_type: 
    - No Parking
    - Above grade, within footprint of main structure
    - Above grade, attached to main structure
    - Below Grade
  bldg_prim_use: 
    - Office
    - Education
    - "Residential: Multifamily (5 or more units)"
    - Public Assembly
    - Laboratory
    - Warehouse and Storage
    - Healthcare
    - Public Order and Safety
    - Transportation Hub
    - Lodging
    - Mercantile
    - Parking
    - Industrial
    - Food Service
    - Religious Worship
    - Other
  bldg_sec_use:
    - Mercantile
    - Office
    - Other
    - Public Assembly
    - Education
    - Food Service
    - Education
    - Warehouse and Storage
    - Laboratory
    - Healthcare
    - Public Order and Safety
    - Religious Worship
    - "Residential: Multifamily (2-4 units)"
  bldg_stories_above:
    - 1 story
    - 2 to 5 stories
    - 6 to 10 stories
    - 11 to 15 stories
    - 16 to 20 stories
    - 21 or more stories
  bldg_stories_below:
    - 0 stories
    - 1 story
    - 2 stories
    - 3 stories
    - 4 or more stories
  bldg_height:
    - 0-7.5 m
    - 7.6-15 m
    - 15.1-22.5 m
    - 22.6-30 m
    - 31-45 m
    - 46-60 m
    - 61-90 m
    - Over 90 m
  str_seis_site_cls:
    - A
    - B
    - C
    - D
    - E
    - F
  str_sdc:
    - A
    - B
    - C
    - D
    - E
    - F
  str_prim_horiz_sys:
    - "Concrete: PT framing"
    - "Concrete: Non-PT framing"
    - "Concrete: Precast"
    - "Concrete: Other"
    - "Steel: Frame + concrete on metal deck"
    - "Steel: Frame + bare metal deck"
    - "Steel: Other"
    - "Wood: Joists and sheathing"
    - "Wood: Engineered panels"
    - "Wood: Other"
  str_prim_vert_sys:
    - "Concrete: CIP"
    - "Concrete: Precast"
    - "Concrete: Other"
    - "Steel: Columns"
    - "Steel: Cold-formed"
    - "Wood: Mass timber"
    - "Wood: Light-frame"
    - "Wood: Other"
    - Masonry
  str_lat_sys:
    - "Concrete: Shear walls"
    - "Concrete: Moment frames"
    - "Concrete: Other"
    - "Steel: Braced frames"
    - "Steel: Moment frames"
    - "Steel: Other"
    - Light Frame shear panels
    - "Masonry: Shear walls"
    - "Wood: Shear panels"
    - "Wood: Other"
  str_podium:
    - Not a podium building
    - Primary system defined above is on a podium
    - Primary system defined above is a podium
  str_fdn_type:
    - Shallow foundation
    - Deep foundation < 50' (15m)
    - Deep foundation > 50' (15m)
    - Other Foundation System
  str_sys_summary:
    - Concrete
    - Steel
    - Steel/Concrete
    - Steel/Masonry
    - "Wood: Mass Timber"
    - "Wood: Light-frame"
    - Other
  lca_design_phase:
    - Design Development
    - Construction Documents
    - Construction
    - Completed
  lca_software:
    - Tally LCA
    - One Click LCA
  lca_purp_of_assessment:
    - "Required: Client Directive"
    - "Required: Governing Policy"
    - "Required: LEED Proposed"
    - "Required: ILFI Proposed"
    - "Required: Other"
    - "Voluntary: Design Milestone Tracking"
    - "Voluntary: Hot Spot Analysis"
    - "Voluntary: Performance Declaration"
    - "Voluntary: Design Iteration Analysis"
    - "Voluntary: Internal Benchmarking"
    - "Voluntary: Other"
  lca_phys_scope:
    - BSE
    - BSEC
    - BSEF
    - BSECF
    - SCF
    - ECF
    - SEC
    - SECF
    - CF
  lca_ec_reductions:
    - Yes
    - No

caption_orders:
  scope_order:
    - Substructure
    - "Shell - Superstructure"
    - "Shell - Enclosure"
    - "Interiors - Construction"
    - "Interiors - Finishes"
    - Unknown
  proj_type_order:
    - New Construction
    - Major Renovation
    - Minor Renovation
    - Tenant Improvement

material_list: 
  - Acoustic ceilings
  - Adhesives and sealants
  - Air and vapor barriers
  - Aluminum
  - Applied fireproofing
  - Cladding
  - Coatings
  - Concrete
  - Doors and frames
  - Flooring and tile
  - Glazing
  - Gypsum
  - Insulation  
  - Masonry
  - Other
  - Other metals
  - Roofing and waterproofing
  - Steel
  - Synthetic composites
  - Wall coverings
  - Windows and frames
  - Wood and composites
